name: "pr-comment"
on: # rebuild any PRs and main branch changes
  issue_comment:
    types: [created]

jobs:
  run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - run: cat $GITHUB_EVENT_PATH | jq '.comment.body' | if [ /dev/stdin == 'Hi' ] then echo ::set-output name=ok::true fi
    - name: reply
      if: inputs.name
      run: echo Hi hi