name: "pr-comment"
on: # rebuild any PRs and main branch changes
  issue_comment:
    types: [created]

jobs:
  run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        who-to-greet: workflows
    - run: echo $GITHUB_EVENT_PATH